#docker-compose.yaml
version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: monke-db
    volumes:
      - ./db:/data/db:rw
    networks:
      - monkedbnet

  web:
    image: node:latest
    container_name: monke-web
    volumes:
      - ./FrontEnd:/app
    depends_on:
      - db
    networks:
      - monkenet
      - monkedbnet
    working_dir: /app
    command: "npm start"

  nginx:
    image: nginx:latest
    container_name: monke-nginx-container
    volumes:
      - ./FrontEnd/public:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ngix_logs:/var/log/nginx
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./ssl_certs/public_nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl_certs/private_nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - monkenet

networks:
  monkenet:
    driver: bridge
