version: "3.8"

services:
  front:
    container_name: monke-next
    build: ./FrontEnd
    volumes:
      - type: volume
        source: db
        target: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: ./BackEnd
    container_name: monke-db
    volumes:
      - ./db:/data/db:rw
    environment:
      port: 27017

  nginx:
    image: nginx:latest
    container_name: my-nginx-container
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ngix_logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - web

# Define secrets
secrets:
  postgres_password:
    file: ./cred.txt

# Define volumes
volumes:
  db:
